name:                icfpc2020-powder
version:             0.1.0.0
github:              "mniip/icfpc2020"


dependencies:
- base >= 4.7 && < 5
- http-conduit >= 2.3
- utf8-string >= 1.0
- bytestring >= 0.10
- binary >= 0.8

library:
  source-dirs: .

executables:
  main:
    main:                Main.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder]
    ghc-options: [-O2]
  encode:
    main:                Encode.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder]
    ghc-options: [-O2]
  decode:
    main:                Decode.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder]
    ghc-options: [-O2]
  cleanse:
    main:                Cleanse.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder]
    ghc-options: [-O2]
