name:                icfpc2020-powder-meta
version:             0.1.0.0
github:              "mniip/icfpc2020"


dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- http-conduit >= 2.3
- utf8-string >= 1.0
- bytestring >= 0.10
- binary >= 0.8
- split >= 0.2
- transformers >= 0.5
- array >= 0.5
- unordered-containers >= 0.2

library:
  source-dirs: .

executables:
  encode:
    main:                Encode.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder-meta]
    ghc-options: [-O2]
  decode:
    main:                Decode.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder-meta]
    ghc-options: [-O2]
  cleanse:
    main:                Cleanse.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder-meta]
    ghc-options: [-O2]
  run:
    main:                Run.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder-meta]
    ghc-options: [-O2]
  interact:
    main:                Interact.hs
    source-dirs: app
    other-modules: []
    dependencies: [icfpc2020-powder-meta]
    ghc-options: [-O2]
